<?php

/**
 * @file
 * Provides online application, selection, and assignment functions
 */
require_once (DRUPAL_ROOT . '/vendor/autoload.php');
/**
 * Implementation of hook_help().
 */
function trip_admin_help($path, $arg) {
  switch ($path) {
    case 'admin/help#trip_admin':
      $output = '<p>' . t('Provides online application functions including the online application, the ability for trip leaders to rank applicants, and the ability to sort applicants into trips based on applicant and trip leader rankings.') . '</p>';
    return $output;
  }
}

/**
 * Implementation of hook_permission().
 */
function trip_admin_permission() {
  return array(
    'administer all application processes' => array(
      'title' => t('Administer all application processes'),
      'description' => t('Perform administration all application processes.'),
    ),

  );
}
/**
 * Implements hook_theme().
 */
function trip_admin_theme($existing, $type, $theme, $path) {
  $path = drupal_get_path('module', 'trip_admin');
  $themes = array (
    'current_trips' => array(
      'template' => 'theme/current_trips',
      'arguments' => array('app_pro'=>NULL, 'trips'=>NULL),
      'path' => $path
    ),
  );
  return $themes;
}

/**
 * Implementation of hook_form_alter().
 */
function trip_admin_form_alter(&$form, &$form_state, $form_id) {

  if($form_id == 'views_form_applications_page_1'){
    $form['actions']['submit']['#submit'][] = '_trip_admin_update_ranks_submit';
  }


  if($form_id == 'trip_application_node_form'){

    $is_new = empty($form['nid']['#value']);

    if($is_new) {

    }

    $form['#validate'][] = 'trip_admin_application_form_validate';

  }

}
function trip_admin_application_form_validate($form, &$form_state) {
  // Random example, if the title is 'test' throw an error
  //if ($form_state['values']['title'] == 'test') {
   // form_set_error('title', 'Title cannot be "test"');
 // }
  //dsm($form_state['values']);
  global $user;

  $app_pro = $form_state['values']['field_tripapp_appro'][LANGUAGE_NONE][0]['target_id'];
  $trip = $form_state['values']['field_tripapp_trip'][LANGUAGE_NONE][0]['target_id'];
  $pref = $form_state['values']['field_tripapp_pref'][LANGUAGE_NONE][0]['value'];
  $is_new = (empty($form_state['values']['nid']));
  //form_set_error('title','test');
  $applied = trip_admin_current_applications($app_pro, $user->uid);
  form_set_error('title',print_r($applied,TRUE));
  if($is_new) {
    if (count($applied) >= 3) {
      form_set_error('field_tripapp_pref', 'Maximum number of trip applications (3) reached');
      return;
    }
    foreach ($applied as $tid => $p) {
      if($trip == $tid){
        $node = node_load($tid);
        form_set_error('field_tripapp_pref', 'Already applied for this trip '. $node->title);
        return;
      }
      elseif ($p == $pref) {
        $node = node_load($tid);
        form_set_error('field_tripapp_pref', 'Already applied for '. $node->title . ' with preference '. $p);
        return;
      }
    }
  }
  else {
    foreach ($applied as $tid => $p) {
      if($p == $pref && $tid != $trip) {
        $node = node_load($tid);
        form_set_error('field_tripapp_pref', 'Already applied for '. $node->title . ' with preference '. $p);
        return;
      }
    }
  }

}

function trip_admin_current_applications($app_pro, $uid) {
  $sql = <<< EOF
select t.field_tripapp_trip_target_id trip, p.field_tripapp_pref_value pre
from field_data_field_tripapp_pref p ,
field_data_field_tripapp_appro pro, field_data_field_tripapp_trip t , node tan
where pro.field_tripapp_appro_target_id = :app_pro and pro.bundle='trip_application'
and t.entity_type='node' and t.entity_id=pro.entity_id
and p.entity_type='node' and p.entity_id=pro.entity_id
and tan.nid = pro.entity_id and tan.uid = :uid
EOF;
  $result = db_query($sql, array(':app_pro'=>$app_pro, ':uid'=>$uid));

  $r = array();
  while ($row = $result->fetchAssoc()) {
    $r[$row['trip']] = $row['pre'];
  }
  return $r;
}

function trip_admin_last_answers($app_pro, $uid) {
  $sql = <<< EOF
select q1.field_question_1_value a1, q2.field_question_2_a_value a2
from 
field_data_field_tripapp_appro pro
 inner join  node tan on tan.nid = pro.entity_id and tan.uid = :uid
 left join field_data_field_question_1 q1 on q1.entity_type='node' and q1.entity_id=pro.entity_id
 left join field_data_field_question_2_a q2 on q2.entity_type='node' and q2.entity_id=pro.entity_id
where pro.field_tripapp_appro_target_id = :app_pro and pro.bundle='trip_application'
order by tan.created desc limit 1
EOF;
  $result = db_query($sql, array(':app_pro'=>$app_pro, ':uid'=>$uid));


  if ($row = $result->fetchAssoc()) {
    return $row;
  }
  return array('a1'=>"", 'a2'=>"");
}

function trip_admin_node_access($node, $op, $account) {
  $type = is_string($node) ? $node : $node->type;
  if ($type == 'trip_application' && ($op == 'create')) {
    if(!in_array('admin', $GLOBALS['user']->roles)
      && !in_array('trip program director', $GLOBALS['user']->roles)
      && !in_array('Stanford Staff', $GLOBALS['user']->roles)
      && !in_array('Stanford Faculty', $GLOBALS['user']->roles)
      ){

      if(!isset($_GET['field_tripapp_appro'])){
        return NODE_ACCESS_DENY;
      }

      $result = db_select('node', 'n')
            ->fields('n')
            ->condition('n.type','trip_application','=')
            ->condition('n.uid',$GLOBALS['user']->uid,'=');

      $result->join('field_data_field_tripapp_appro', 'f', 'f.bundle = n.type AND f.entity_id = n.nid');
      $result->condition('f.field_tripapp_appro_target_id',$_GET['field_tripapp_appro'],'=');


      $result = $result->execute();
      $num_of_results = $result->rowCount();
      if($num_of_results >= 3){
       return NODE_ACCESS_DENY;
      }
    }

  }

  return NODE_ACCESS_IGNORE;
}


function _trip_admin_update_ranks_submit(&$form, &$form_state){

  foreach($form_state['values']['draggableviews'] as $item){
    $node = node_load($item['id']);
    $node->field_tripapp_rank['und'][0]['value'] = $item['weight'] + 1;
    node_save($node);
  }
}




/**
 * Implementation of hook_menu().
 */

function trip_admin_menu() {

  $items['node/%node/trips'] = array(
    'title' => t("Trips"),
    'description' => t("View trips for this application process."),
    'access callback' => '_trip_admin_local_tasks',
    'access arguments' => array(1, 'trips'),
    'page callback' => 'trip_admin_apppro_trips',
    'page arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'weight' => 3,
  );

  $items['node/%node/sort'] = array(
    'title' => t("Sort"),
    'description' => t("Sort applicants into trips."),
    'access callback' => '_trip_admin_local_tasks',
    'access arguments' => array(1, 'sort'),
    'page callback' => 'trip_admin_apppro_sort',
    'page arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'weight' => 5,
  );
  $items['node/%node/download.xlsx'] = array(
    'title' => t("Download"),
    'description' => t("Download applicants"),
    'access callback' => '_trip_admin_local_tasks',
    'access arguments' => array(1, 'download'),
    'page callback' => 'trip_admin_apppro_download',
    'page arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'weight' => 6,
  );
  $items['admin/config/asb'] = array(
    'title' => 'ASB config',
    'description' => 'Configuration for ASB',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('trip_admin_config_form'),
    'access arguments' => array('administer all application processes'),
    'type' => MENU_NORMAL_ITEM,
  );


  return $items;
}

function trip_admin_config_form($form, &$form_state) {
  $sql = <<< EOF
select
  n.nid, n.title from node n where n.type='app_process' and n.status=1
order by n.created desc 
EOF;
  $result = db_query($sql, array());

  $options = array(0 => ' - None - ');
  while ($row = $result->fetchAssoc()) {
    $options[$row['nid']] = $row['title'];
  }
  $form['trip_admin_active_asb'] = array(
    '#type' => 'select',
    '#title' => t('Active ASB'),
    '#default_value' => variable_get('trip_admin_active_asb', 0),
    '#options' => $options,
    '#description' => t('Active ASB'),
    '#required' => TRUE,
  );
  $form['trip_admin_active_tgb'] = array(
    '#type' => 'select',
    '#title' => t('Active TGB'),
    '#default_value' => variable_get('trip_admin_active_tgb', 0),
    '#options' => $options,
    '#description' => t('Active TGB'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
 * Custom access control for local tasks based on node type
 */
function _trip_admin_local_tasks($node, $task) {
  global $user;

  switch ($node->type) {
    case 'app_process':
      switch ($task) {
        case 'sort':
        case 'trips':
        case 'download':
          if (user_access('administer all application processes')) {
            return TRUE;
          }
        default:
          return FALSE;
      }
      break;
    default:
      return FALSE;
  }
}


function trip_admin_apppro_trips($node) {
  $trips = views_get_view('trips_for_app_process');
  $trips->set_arguments(array($node->nid));
  $trips_output = $trips->preview();
  $trips_data = $trips->result;
  $output = '';
  $output .= '<p>' . l('Create a new trip', 'node/add/trip') . '</p>';

  if ($trips_data) {
    $output .= "<p>Below are the trips associated with this application
      process.</p>";
    $output .= $trips_output;
  }
  else {
    $output .= t('<p>There are no trips yet for this application
    process.</p>');
  }

  return $output;
}

function trip_admin_apppro_sort($apppro) {

  $fied_status = field_get_items('node',$apppro,'field_apppro_status');
  $output = '';
  if ($fied_status[0]['value'] != 'closed') {
    $output .= t('Applications and/or ranking for this application
      process are currently open.  They both must be closed in order to sort
      applicants into trips.  Please close them by selecting the <em>edit</em>
      tab above and try again.');
  }
  else {
    $output .= t('<p>This process will sort the applicants into trips.  After this
      process runs, you will be able to manually review and edit trip rosters.  You
       may run this process multiple times if for some reason a sort does not work out.
      <strong>If you have already run the sorting process for
      this application process and are running it again, please be aware that
      any manual rearrangements you made to the trip rosters or waitlists
      will be lost.</strong></p>');
    $output .= t('<p><strong>Please confirm that all leaders have entered their rankings!
    If a leader has not entered any rankings, they will be assigned no participants.</strong>
    If a leader has not entered rankings before you run the sort, open the ranking again,
    have the leader enter rankings, and then re-run the sort.');
    $output .= t('<p>Please review the settings for this application process one
      more time before running the sort.  If you need to make any changes, select
      the <em>edit</em> tab above.</p>');
    $elements = node_view($apppro);
    $output .= drupal_render($elements);
    $output .= '<p>Sorting may take a minute or two.  Would you like to continue?</p>';
    $elements = drupal_get_form('_trip_admin_apppro_sort_form', $apppro->nid);
    $output .= drupal_render($elements);
  }

  return $output;
}

function _trip_admin_apppro_sort_form($form, &$form_state, $apppro_nid) {

  $form['apppro_nid'] = array(
    '#type' => 'value',
    '#value' => $apppro_nid,
  );

  $form['yes'] = array(
    '#type' => 'submit',
    '#value' => t('Yes'),
    '#prefix' => '<div class="container-inline">',
  );

  $form['no'] = array(
    '#type' => 'submit',
    '#value' => t('No'),
    '#suffix' => '</div>',
  );

  return $form;
}


function _trip_admin_apppro_sort_form_submit($form, &$form_state) {
  if ($form_state['clicked_button']['#value'] == 'Yes') {
    $apppro_nid = $form_state['values']['apppro_nid'];
    _trip_admin_new_sort($apppro_nid);
    return;
    $accepted_table = $apppro_nid . "_applicants_accepted";
    $data_table = $apppro_nid . "_applicants_data";

    _trip_admin_apppro_sort_tables($apppro_nid, $data_table, $accepted_table);

    _trip_admin_apppro_sort_sort($apppro_nid, $data_table, $accepted_table);
    _trip_admin_apppro_sort_waitlist($apppro_nid, $data_table);

    batch_set(_trip_admin_apppro_sort_save($apppro_nid, $data_table));

  }
  else {
    drupal_set_message(t('Sorting was not performed.'));
  }
}
/*
 * Copyright Anne Shor
 * anneshor@stanford.edu
 */
function _trip_admin_new_sort($apppro_nid) {
  $app_proc_node = node_load($apppro_nid);


  $sql = <<< EOF
select distinct
appro.entity_id trip_id,
num.field_trip_num_participants_value num

 from field_data_field_trip_apppro appro 
inner join node na on na.nid = appro.entity_id and na.status=1
inner join field_data_field_trip_num_participants num on num.entity_id=appro.entity_id


where appro.field_trip_apppro_target_id = :nid and appro.bundle = 'trip'
EOF;
  $result = db_query($sql, array(':nid'=>$apppro_nid));
  $trips = [];
  while ($row = $result->fetchAssoc()) {
    $row['apps'] = [];
    $trips[$row['trip_id']] = $row;

  }
  $users = [];
  $sql = <<< EOF
select
appro.entity_id app_id,
trip.field_tripapp_trip_target_id trip_id,
na.uid,
pref.field_tripapp_pref_value preference,
r.field_tripapp_rank_value rank

 from field_data_field_tripapp_appro appro 
inner join node na on na.nid = appro.entity_id and na.status=1
inner join field_data_field_tripapp_trip trip on trip.entity_id=appro.entity_id
inner join field_data_field_tripapp_pref pref on pref.entity_id=appro.entity_id
inner join field_data_field_tripapp_rank r on r.entity_id=appro.entity_id

where appro.field_tripapp_appro_target_id = :nid and appro.bundle = 'trip_application'
order by trip.field_tripapp_trip_target_id, r.field_tripapp_rank_value
EOF;
  $result = db_query($sql, array(':nid'=>$apppro_nid));
  $apps = [];
  while ($row = $result->fetchAssoc()) {
    $row['status'] = 0;
    $apps[$row['app_id']] = $row;
    $trips[$row['trip_id']]['apps'][$row['app_id']] = $row;
    if(array_key_exists($row['uid'], $users)){
      $users[$row['uid']]['trips'][$row['trip_id']] = $row;
    } else {
      $users[$row['uid']] = ['trips' => [$row['trip_id']=>$row], 'offered' => []];
    }

  }

  while (TRUE) {
    $available = FALSE;
    foreach ($trips as $trip_id => $trip) {
      $stat = _trip_admin_trip_state($trips[$trip_id]);
      if((intval($trip['num']) > $stat['accepted']) && count($stat['available']) > 0){
        $available = TRUE;
        $n = intval($trip['num'])  -  $stat['accepted'] ;
        $i = 0;

        foreach ($stat['available'] as $av_id => $av_app) {
          $users[$av_app['uid']]['offered'][] = $trip_id;

          $i++;
          if ($i == $n) {
            break;
          }
        }

      }

    }

    if (!$available) {
      break;
    }
    foreach ($users as $uid => $u) {
      if (!empty($u['offered'])) {
        $tid = 0;
        $r = -1;
        foreach ($u['offered'] as $trip_id) {
          if($r == -1 || $u['trips'][$trip_id]['preference'] < $r) {
            $tid = $trip_id;
            $r = $u['trips'][$trip_id]['preference'];
          }
        }
        if($tid > 0) {
          foreach ($u['trips'] as $trip_id=>$trip) {
            if($trip_id == $tid) {
              $users[$uid]['trips'][$trip_id]['status'] = 3;
              $trips[$trip_id]['apps'][$u['trips'][$trip_id]['app_id']]['status'] = 3;
            }
            else {
              $trips[$trip_id]['apps'][$u['trips'][$trip_id]['app_id']]['status'] = -1;
              unset($users[$uid]['trips'][$trip_id]);
            }
          }
        }
        $users[$uid]['offered'] = [];
      }
    }
  }



  $wlist_size = intval( $app_proc_node->field_apppro_waitlist_size[LANGUAGE_NONE][0]['value']);

  while (TRUE) {
    $available = FALSE;
    foreach ($trips as $trip_id => $trip) {
      $stat = _trip_admin_trip_state($trip);
      if(($wlist_size > $stat['waitlisted']) && count($stat['available']) > 0){
        $available = TRUE;
        $n = $wlist_size  -  $stat['waitlisted'] ;
        $i = 0;

        foreach ($stat['available'] as $av_id => $av_app) {
          $users[$av_app['uid']]['offered'][] = $trip_id;
          $i++;
          if ($i == $n) {
            break;
          }
        }

      }

    }

    if (!$available) {
      break;
    }
    foreach ($users as $uid => $u) {
      if (!empty($u['offered'])) {
        $tid = 0;
        $r = -1;
        foreach ($u['offered'] as $trip_id) {
          if($r == -1 || $u['trips'][$trip_id]['preference'] < $r) {
            $tid = $trip_id;
            $r = $u['trips'][$trip_id]['preference'];
          }
        }
        if($tid > 0) {
          foreach ($u['trips'] as $trip_id=>$trip) {
            if($trip_id == $tid) {
              $users[$uid]['trips'][$trip_id]['status'] = 2;
              $trips[$trip_id]['apps'][$u['trips'][$trip_id]['app_id']]['status'] = 2;
            }
            else {
              $trips[$trip_id]['apps'][$u['trips'][$trip_id]['app_id']]['status'] = -1;
              unset($users[$uid]['trips'][$trip_id]);
            }
          }
        }
        $users[$uid]['offered'] = [];
      }
    }
  }

  $map = [
    3 => 'Accepted',
    0 => 'Rejected',
    2 => 'Waitlisted',
    -1 => 'Withdrawn'
  ];
  foreach ($trips as $tid => $trip) {

    foreach ($trip['apps'] as $app_id => $a) {
      $app = node_load($app_id);
      $app->field_tripapp_status[LANGUAGE_NONE][0]['value'] =$map[$a['status']];
      node_save($app);

    }

  }
  drupal_set_message(t('The applicants have been sorted into trips and
    waitlists built.  You may view all applicants for all trips by
    selecting the <em>Roster Admin</em> tab above.  You may also view
    applicants for a specific trip by selecting the trip from the
    <em>Trips</em> tab above and selecting its <em>Roster</em> tab.'));
}

function _trip_admin_trip_state($trip) {
  $accepted = 0;
  $waitlisted = 0;
  $available = [];
  foreach ($trip['apps'] as $app_id => $app) {
    if($app['status'] == -1) {
      continue;
    }
    if($app['status'] == 3) {
      $accepted++;
    }
    else if($app['status'] == 2) {
      $waitlisted++;
    }
    else {
      $available[$app_id] = $app;
    }
  }
  return ['accepted'=>$accepted, 'waitlisted'=>$waitlisted, 'available'=>$available];
}


function _trip_admin_apppro_sort_tables($apppro_nid, $data_table, $accepted_table) {
  //create a temporary table to store applicants for the current
  //process given a rank.  If they weren't ranked by any leader, they definitely
  //won't be accepted.

  db_query("DROP TABLE IF EXISTS {$accepted_table}");
  db_query("DROP TABLE IF EXISTS {$data_table}");

  $success = db_query("CREATE TABLE {$accepted_table}
  (`tripapp_nid` int(10), `uid` int(10), `trip_nid` int(10), `preference` int(2), `rank` int(2))");

  //create another temporary table to store the data from the nodes and
  //set accepted status for everyone for current year to be 0.  This avoids
  //using a billion node_load and node_save calls.
  $success = db_query("CREATE TABLE {$data_table}
    (`tripapp_nid` int(10), `uid` int(10), `trip_nid` int(10), `preference` int(2), `rank` int(2), `accepted` tinyint(1) default 0, `waitlisted` tinyint(1) default 0)");

  $tripapps = views_get_view('tripapps_for_apppro');
  $tripapps->set_arguments(array($apppro_nid));
  $tripapps->preview();
  $tripapps_data = $tripapps->result;
  $data_insert_substring = '';
  $accepted_insert_substring = '';
  foreach ($tripapps_data as $tripapp) {
    $trip = isset($tripapp->field_field_tripapp_trip[0]['raw']['target_id']) ? $tripapp->field_field_tripapp_trip[0]['raw']['target_id'] : "0";
    $pref = isset($tripapp->field_field_tripapp_pref[0]['raw']['value']) ? $tripapp->field_field_tripapp_pref[0]['raw']['value'] : "0";
    $rank = isset($tripapp->field_field_tripapp_rank[0]['raw']['value']) ? $tripapp->field_field_tripapp_rank[0]['raw']['value'] : "0";
    $data_insert_substring .= "(" .
      $tripapp->nid . "," .
      $tripapp->node_uid . "," .
      $trip . "," .
      $pref . "," .
      $rank . "),\n";
    if ($rank > 0) {
      $accepted_insert_substring .= "(" .
        $tripapp->nid . "," .
        $tripapp->node_uid . "," .
        $trip . "," .
        $pref . "," .
        $rank . "),\n";
    }
  }

  $accepted_insert_substring = substr($accepted_insert_substring,0,-2);
  $data_insert_substring = substr($data_insert_substring,0,-2);

  if ($accepted_insert_substring) {
    $success = db_query("INSERT INTO {$accepted_table}
      (`tripapp_nid`, `uid`, `trip_nid`, `preference`, `rank`) VALUES
      $accepted_insert_substring");
  }
  if ($data_insert_substring) {
    $success = db_query("INSERT INTO {$data_table}
      (`tripapp_nid`, `uid`, `trip_nid`, `preference`, `rank`) VALUES
      $data_insert_substring");
  }


  $num_entries = db_query("SELECT COUNT(*) as count FROM {$accepted_table}")->fetchField();
  if (!$num_entries) {
    db_query("DROP TABLE IF EXISTS {$accepted_table}");
    db_query("DROP TABLE IF EXISTS {$data_table}");
    drupal_set_message(t('There are either no applications or no rankings!  Please ensure that there are both applications and rankings before running the sort.'), 'error');
    drupal_goto('node/' . $apppro_nid . '/sort');
  }
}

function _trip_admin_apppro_sort_sort($apppro_nid, $data_table, $accepted_table) {
  //delete all except the applicant's top preference trip for which
  //she or he was ranked
  $previous_uid = 0;
  $applications = db_query("SELECT `uid`, `preference` FROM {$accepted_table} ORDER BY `uid`, `preference`");
  foreach ($applications as $application ) {
    if ($application->uid == $previous_uid) {
      //remove this application because applicant exists in the table
      //for a higher preference trip.
      $success = db_query("DELETE FROM {$accepted_table}
        WHERE `uid` = :uid AND
	`preference` = :pre",array(':uid' => $application->uid, ':pre' => $application->preference));
    }
    $previous_uid = $application->uid;
  }



  //tentatively assign all applicants to the top trip for which they were ranked.
  $success = db_query("UPDATE {$data_table}, {$accepted_table} SET {$data_table}.`accepted` = '1'
    WHERE {$accepted_table}.`uid` = {$data_table}.`uid`
    AND {$accepted_table}.`trip_nid` = {$data_table}.`trip_nid`");


  $moved = 1;
  $trips = views_get_view('trips_data_for_app_process');
  $trips->set_arguments(array($apppro_nid));
  $trips->preview();
  $trips_data = $trips->result;

  while ($moved > 0) {
    $moved = 0;
    foreach ($trips_data as $trip) {
      // how many do we have for this trip?
      $num_applicants = db_query("SELECT COUNT(`uid`) as count FROM
				        {$accepted_table} WHERE `trip_nid` = :tnid",
				         array(':tnid' => $trip->nid))
				      	->fetchField();
      $num_participants = $trip->field_field_trip_num_participants[0]['raw']['value'];
      if ($num_applicants > $num_participants){
      	$dif = $num_applicants - $num_participants;
        // order by rank and move the ones we can't take.
        $leftovers = db_query("SELECT * FROM {$accepted_table}
          WHERE `trip_nid` = :tnid ORDER BY `rank` LIMIT $num_participants, $dif",
          array(':tnid'=> $trip->nid));

        foreach ($leftovers as $leftover) {
          $moved++;
          // set the accepted = 0 for this trip
          $success = db_query("UPDATE {$data_table} SET `accepted` = 0
            WHERE `uid` = :uid AND `trip_nid` = :tnid",
            array(':uid' => $leftover->uid, ':tnid' => $leftover->trip_nid));
	  		// remove this entry from the temporary accepted applications table
          $success = db_query("DELETE FROM {$accepted_table}
            WHERE `uid` = :uid AND `trip_nid` = :tnid",
            array(':uid' => $leftover->uid, ':tnid' => $leftover->trip_nid));

          // check to see if the "leftover" person has another ranked application.
		  // if so, temporarily assign them to that trip
		  // if not, they are sadly not accepted to a trip at all this year
          $next_application = db_query("SELECT * FROM {$data_table}
            WHERE `uid` = :uid AND `preference` > :pref AND `rank` > 0
            ORDER BY `preference` LIMIT 1",
            array(':uid' => $leftover->uid, ':pref' => $leftover->preference))->fetchObject();

          if ($next_application) {
            $success = db_update($data_table)
					  ->fields(array('accepted' => 1))
					  ->condition('uid', $next_application->uid, '=')
					  ->condition('trip_nid', $next_application->trip_nid, '=')
					  ->execute();
            $success = db_insert($accepted_table)
						->fields(array(
						  'uid' => $next_application->uid,
						  'trip_nid' => $next_application->trip_nid,
						  'preference' => $next_application->preference,
						  'rank' => $next_application->rank
						))
						->execute();
          }
        }
      }
    }
  }
  db_query("DROP TABLE IF EXISTS {$accepted_table}");
}

function _trip_admin_apppro_sort_waitlist($apppro_nid, $data_table) {
  $apppro_node = node_load($apppro_nid);
  $fied_waitlist = field_get_items('node',$apppro_node,'field_apppro_waitlist_size');
  $trips = db_query("SELECT DISTINCT `trip_nid` FROM {$data_table} WHERE `accepted` != 1");

  foreach ($trips as $trip) {
    $tripapps = db_query("SELECT * FROM {$data_table}
      WHERE `trip_nid` = :tnid AND `rank` > 0
      AND `uid` NOT IN
        (SELECT `uid` FROM {$data_table} WHERE `accepted` = '1')
      ORDER BY `rank` LIMIT {$fied_waitlist[0]['value']}", array( ':tnid' => $trip->trip_nid));

    foreach ($tripapps as $tripapp) {
      $success =  db_update($data_table)
      			  ->fields(array('waitlisted' => 1))
      			  ->condition('tripapp_nid', $tripapp->tripapp_nid, '=')
      			  ->execute();
    }
  }
}

function _trip_admin_apppro_sort_save($apppro_nid, $data_table) {
  $operations = array();
  $operations[] = array('_trip_admin_apppro_sort_save_batch', array($apppro_nid, $data_table));
  $batch = array(
    'operations' => $operations,
    'finished' => '_trip_admin_apppro_sort_finished',
    'title' => t('Processing Sort Save'),
    'init_message' => t('Save is starting.'),
    'progress_message' => t('Completed @current out of @total task(s).'),
    'error_message' => t('Some records were unable to be saved.'),
  );
  return $batch;
}

function _trip_admin_apppro_sort_save_batch($apppro_nid, $data_table, &$context) {
  if (!isset($context['sandbox']['progress'])) {
    $context['sandbox']['progress'] = 0;
    $context['sandbox']['current_row'] = 0;
    $context['sandbox']['max'] = db_query("SELECT COUNT(DISTINCT `tripapp_nid`) as count FROM {$data_table}")->fetchField();
  }
  $limit = 100;

  $revised_tripapps_data = db_query_range("SELECT `tripapp_nid`,
  `accepted`, `waitlisted` FROM {$data_table} ORDER BY `tripapp_nid`",
  $context['sandbox']['current_row'], $limit);

  foreach ($revised_tripapps_data as $revised_tripapp) {
     $status = 'Rejected';
    if ($revised_tripapp->accepted) {
      $status = 'Accepted';
    }
    else if ($revised_tripapp->waitlisted) {
      $status = 'Waitlisted';
    }

    $tripapp_node = node_load($revised_tripapp->tripapp_nid, NULL, TRUE);
    $tripapp_node->field_tripapp_status['und'][0]['value'] = $status;
    node_save($tripapp_node);


    //$tripapp_node = node_load($tripapp->nid, NULL, TRUE);
    // Update our progress information.
    $context['sandbox']['progress']++;
    $context['sandbox']['current_row']++;
    $context['message'] = t('Saving record @record of @max_records',
    array('@record' => $context['sandbox']['current_row'],
    '@max_records' => $context['sandbox']['max']));
  }
  $context['results'] = $data_table;

  if ($context['sandbox']['progress'] < $context['sandbox']['max']) {
    $context['finished'] = $context['sandbox']['progress'] / $context['sandbox']['max'];
  }
}

function _trip_admin_apppro_sort_finished($success, $results, $operations) {
  db_query("DROP TABLE IF EXISTS " . $results);

  drupal_set_message(t('The applicants have been sorted into trips and
    waitlists built.  You may view all applicants for all trips by
    selecting the <em>Roster Admin</em> tab above.  You may also view
    applicants for a specific trip by selecting the trip from the
    <em>Trips</em> tab above and selecting its <em>Roster</em> tab.'));
}

function trip_admin_apppro_download($apppro) {
  $app = trip_admin_apppro_roster($apppro);
  $phpExcel = new PHPExcel;
  $writer = PHPExcel_IOFactory::createWriter($phpExcel, "Excel2007");
  $sheet = $phpExcel ->getActiveSheet();
  $sheet->setTitle('Roster');
  $header_style = [
    'font' => [
      'size'=>14,
      'bold'=>1,

    ],
    'fill' => [
      'type' => PHPExcel_Style_Fill::FILL_SOLID,
      'color'=> [
        'rgb'=>'00FF00'
      ]
    ]
  ];
  $header2_style = [
    'font' => [
      'size'=>12,
      'bold'=>1,

    ],
    'fill' => [
      'type' => PHPExcel_Style_Fill::FILL_SOLID,
      'color'=> [
        'rgb'=>'00FFFF'
      ]
    ]
  ];
  $header3_style = [
    'font' => [
      'size'=>14,
      'bold'=>1,

    ],
    'fill' => [
      'type' => PHPExcel_Style_Fill::FILL_SOLID,
      'color'=> [
        'rgb'=>'FF0000'
      ]
    ]
  ];

  $accepted_style = [
    'font' => [
      'size'=>12,

    ],
    'fill' => [
      'type' => PHPExcel_Style_Fill::FILL_SOLID,
      'color'=> [
        'rgb'=>'EA9999'
      ]
    ]
  ];

  $wlisted_style = [
    'font' => [
      'size'=>12,
    ],
    'fill' => [
      'type' => PHPExcel_Style_Fill::FILL_SOLID,
      'color'=> [
        'rgb'=>'FFFF00'
      ]
    ]
  ];

  $rejected_style = [
    'font' => [
      'size'=>12,

    ],
    'fill' => [
      'type' => PHPExcel_Style_Fill::FILL_SOLID,
      'color'=> [
        'rgb'=>'FF9900'
      ]
    ]
  ];

  $max = 0;
  $i = 0;
  $count_trips = count($app['trips']);
  $sheet->getStyleByColumnAndRow(0,1,2*$count_trips -1,1)
    ->applyFromArray($header_style);
  $sheet->getStyleByColumnAndRow(0,2,2*$count_trips -1,2)
    ->applyFromArray($header2_style);

  foreach ($app['trips'] as $trip) {
    $sheet->getCellByColumnAndRow($i*2,1)->setValue($trip['title']);
    $sheet ->getCellByColumnAndRow($i*2,2)->setValue('Participants');
    $sheet ->getCellByColumnAndRow($i*2+1,2)->setValue('Emails');

    $sheet->mergeCellsByColumnAndRow(2*$i,1,2*$i+1,1);
    $j = 0;
    foreach ($trip['accepted'] as $p) {
      $sheet->getCellByColumnAndRow($i*2,3+$j)->setValue($p['name']);
      $sheet->getCellByColumnAndRow($i*2+1,3+$j)->setValue($p['mail']);
      $j++;
    }
    foreach ($trip['wlisted'] as $p) {
      $sheet->getCellByColumnAndRow($i*2,3+$j)->setValue($p['name']);
      $sheet->getCellByColumnAndRow($i*2+1,3+$j)->setValue($p['mail']);
      $j++;
    }
    if ($max < $j) {
      $max = $j;
    }
    $sheet->getStyleByColumnAndRow($i*2,3,
      $i*2+1,2+count($trip['accepted']))
      ->applyFromArray($accepted_style);
    $sheet->getStyleByColumnAndRow($i*2,3+count($trip['accepted']),
      $i*2+1,2 +count($trip['accepted'])+count($trip['wlisted']))
      ->applyFromArray($wlisted_style);
    $i++;
  }

  $N = $max + 6;
  $sheet->getStyleByColumnAndRow(0,$N)
    ->applyFromArray($header3_style);
  $sheet->getCellByColumnAndRow(0,$N)->setValue('Rejections');

  $sheet->getStyleByColumnAndRow(0,$N+1, 1,$N+1)
    ->applyFromArray($header2_style);

  $sheet->getCellByColumnAndRow(0,$N+1)->setValue('Participants');
  $sheet->getCellByColumnAndRow(1,$N+1)->setValue('Emails');

  $sheet->getStyleByColumnAndRow(0,$N+2, 1,$N+1+ count($app['rejected']))
    ->applyFromArray($rejected_style);
  $j = 0;
  foreach ($app['rejected'] as $p) {
    $sheet->getCellByColumnAndRow(0,$N+2+$j)->setValue($p['name']);
    $sheet->getCellByColumnAndRow(1,$N+2+$j)->setValue($p['mail']);
    $j++;
  }
/*
  dsm($app);
  $writer->save('/tmp/products.xlsx');
  return "OK";
*/
  //drupal_add_http_header('Content-Type','application/vnd.ms-excel');

  drupal_add_http_header('Content-disposition','attachment;filename="application_process_'+$apppro->nid+'.xlsx"');

  drupal_add_http_header('Cache-Control','max-age=0');

  $writer->save('php://output');
}

function trip_admin_apppro_roster($apppro) {
  $trips = [];
  $sql = <<< EOF
select 
appro.entity_id trip_id,
na.title

 from field_data_field_trip_apppro appro 
inner join node na on na.nid = appro.entity_id and na.status=1



where appro.field_trip_apppro_target_id = :nid and appro.bundle = 'trip'
EOF;
  ;
  $result = db_query($sql, array(':nid'=>$apppro->nid));

  $trips = [];
  $rejected = [];
  while ($row = $result->fetchAssoc()) {
    $row['accepted'] = [];
    $row['wlisted'] = [];

    $trips[$row['trip_id']] = $row;

  }


  $sql = <<< EOF
select 
ftrip.field_tripapp_trip_target_id trip_id,
na.nid,
na.title,
ar.field_tripapp_rank_value rank,
u.mail,
u.name,
st.field_tripapp_status_value status



 from field_data_field_trip_apppro ap
 inner join field_data_field_tripapp_trip ftrip
  on  ftrip.field_tripapp_trip_target_id = ap.entity_id and  ftrip.entity_type='node'  and  ftrip.bundle='trip_application'
  
inner join node na on na.nid = ftrip.entity_id and na.status=1
left join field_data_field_tripapp_rank ar on ar.entity_type='node' and ar.entity_id=ftrip.entity_id
inner join users u on u.uid = na.uid
left join field_data_field_tripapp_status st on st.entity_type='node' and st.entity_id=ftrip.entity_id


where ap.field_trip_apppro_target_id = :nid and ap.bundle = 'trip'
order by ar.field_tripapp_rank_value
EOF;
  ;
  $result = db_query($sql, array(':nid'=>$apppro->nid));

  while ($row = $result->fetchAssoc()) {
    $trip_id = $row['trip_id'];
    switch ($row['status']) {
      case 'Accepted':
        $trips[$trip_id]['accepted'][] = $row;
        break;
      case 'Waitlisted':
        $trips[$trip_id]['wlisted'][] = $row;
        break;
      case 'Rejected':
        if(!array_key_exists($row['name'], $rejected)) {
          $rejected[$row['name']] = $row;
        }
        break;
    }

  }

  return $app = ['trips'=>$trips, 'rejected'=>$rejected];

}


/**
 * Implements hook_block_info().
 */
function trip_admin_block_info() {
  return array(
    'current_trips' => array(
      'info' => t('Current Trips'),
    )
  );
}

/**
 * Implements hook_block_view().
 */
function trip_admin_block_view($delta = '') {
  $sql = <<< EOF
select n.nid, n.title,
tl.field_trip_location_value trip_location,
td.field_trip_description_value trip_description,
(
select p.field_tripapp_pref_value from field_data_field_tripapp_trip ft , node tn ,
field_data_field_tripapp_pref p
where ft.field_tripapp_trip_target_id = ap.entity_id and ft.bundle='trip_application'
and tn.nid=ft.entity_id and tn.status=1 and tn.uid = :uid
and p.entity_type='node' and p.entity_id=ft.entity_id 

) pref
 from  field_data_field_trip_apppro ap 
inner join node n on n.nid = ap.entity_id and n.status=1
left join field_data_field_trip_location tl on tl.entity_type='node' and tl.entity_id=ap.entity_id
left join field_data_field_trip_description td on td.entity_type='node' and td.entity_id=ap.entity_id
where ap.field_trip_apppro_target_id = :app_pro and ap.bundle='trip'
EOF;
  $block = array();
  switch ($delta) {
    case 'current_trips':
      global $user;
      $tp = arg(1);
      dsm($tp);
      $app_pro_nid = ($tp == '23293' ? variable_get('trip_admin_active_tgb', 0) :
        ($tp == '23292' ? variable_get('trip_admin_active_asb', 0) : 0)
      );

      $app_pro = NULL;
      $trips = array();
      if(!empty($app_pro_nid)) {
        $app_pro = node_load($app_pro_nid);
        if(!empty($app_pro)) {
          $result = db_query($sql, array(':app_pro'=>$app_pro_nid, ':uid'=>$user->uid));

          while ($row = $result->fetchAssoc()) {
            $trips[] = $row;
          }
        }
      }
      $block['title'] = '<none>';
      $block['content'] = theme('current_trips',
        array('app_pro'=>$app_pro, 'trips'=>$trips));

      break;
  }
  return $block;
}

